config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'welcome#index'
  resources :jobs do
    resources :resumes
    collection do
      get :search
      end
  end

  namespace :admin do
   resources :jobs do
    member do
      post :hide
      post :publish
      end
      resources :resumes
    end
 end

  root 'welcome#index'
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
  validates :city, presence: true
  validates :location, presence: true
  validates :field, presence: true
  validates :require_time, presence: true
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}


  scope :published, -> { where(is_hidden: false) }
  scope :recent, -> { order('created_at DESC') }

  has_many :resumes

  def job_publish!
    self.is_hidden = false
    self.save
  end

  def job_hide!
    self.is_hidden = true
    self.save
  end

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :require_is_admin

  layout "admin"

  def index
    #@jobs = Job.published.order('created_at DESC')
    @jobs = case params[:order]
    when 'by_lower_bound'
      Job.published.order('wage_lower_bound DESC').paginate(page: params[:page], per_page:5)
    when 'by_upper_bound'
      Job.published.order('wage_upper_bound DESC').paginate(page: params[:page], per_page:5)
    when 'by_require_time'
      Job.published.order('require_time DESC').paginate(page: params[:page], per_page:5)
    else
      Job.published.recent.paginate(page: params[:page], per_page:5)
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:alert] = "Delete success"
    redirect_to admin_jobs_path
  end

  def hide
    @job = Job.find(params[:id])
    @job.job_hide!

    redirect_to :back
  end

  def publish
    @job = Job.find(params[:id])
    @job.job_publish!

    redirect_to :back
  end


  private
   def job_params
     params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden, :city, :location, :field, :require_time,)
   end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :validate_search_key, only: [:search]

  def index
    #@jobs = Job.published.order('created_at DESC')
    @jobs = case params[:order]
    when 'by_lower_bound'
      Job.published.order('wage_lower_bound DESC').paginate(page: params[:page], per_page:5)
    when 'by_upper_bound'
      Job.published.order('wage_upper_bound DESC').paginate(page: params[:page], per_page:5)
    when 'by_require_time'
      Job.published.order('require_time DESC').paginate(page: params[:page], per_page:5)
    else
      Job.published.recent.paginate(page: params[:page], per_page:5)
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      flash[:warning] = "This job already archieved"
      redirect_to jobs_path
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:alert] = "Delete success"
    redirect_to jobs_path
  end

  def search
      @query = @query_string

      if @query_string.present?
        # search_result = Job.ransack(@search_criteria).result(distinct: true)
        search_result = Job.published.ransack({:title_or_city_or_location_or_field_cont => @query_string}).result(distinct: true)
        # search_result = Job.ransack({{:title_or_field_or_location_or_company_name_cont => @q}}).result(distinct: true)
        @jobs = case params[:order]
        when 'by_lower_bound'
          search_result.published.order('wage_lower_bound DESC').paginate(page: params[:page], per_page:5)
        when 'by_upper_bound'
          search_result.published.order('wage_upper_bound DESC').paginate(page: params[:page], per_page:5)
        when 'by_require_time'
          search_result.published.order('require_time DESC').paginate(page: params[:page], per_page:5)
        else
          search_result.published.recent.paginate(page: params[:page], per_page:5)
        end
        # @jobs = search_result.recent.paginate(page: params[:page], per_page:5)
      else
        # @jobs = Job.published.recent.paginate(page: params[:page], per_page:5)
        @jobs = case params[:order]
        when 'by_lower_bound'
          Job.published.order('wage_lower_bound DESC').paginate(page: params[:page], per_page:5)
        when 'by_upper_bound'
          Job.published.order('wage_upper_bound DESC').paginate(page: params[:page], per_page:5)
        when 'by_require_time'
          Job.published.order('require_time DESC').paginate(page: params[:page], per_page:5)
        else
          Job.published.recent.paginate(page: params[:page], per_page:5)
        end
      end
  end


  protected
   def validate_search_key
    @query_string = params[:query_string].gsub(/\\|\'|\/|\?/, '') if params[:query_string].present?
  end

  def search_criteria(query_string)
    { title_or_description_or_answers_content_cont: query_string }
  end

  private
   def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden, :city, :location, :field, :require_time,)
    # params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
   end



end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_status(job)
    if job.is_hidden
      #{}"(Hidden)"
      content_tag(:span, "", :class => "fa fa-lock")
    else
      "(Public)"
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>
  <div class="form-job">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
    <%= f.input :wage_lower_bound, :label => "薪资下限" %>
    <%= f.input :wage_upper_bound, :label => "薪资上限"  %>
    <%= f.input :contact_email, input_html: { class: "form-control"} %>

  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/jobs/_item.html.erb
<tr>
    <td >
     <%= link_to(job.title, job_path(job)) %>
   </td>
   <td>
     <%= link_to(job.field, job_path(job)) %>
    </td>
    <td>
     <%= link_to(job.city, job_path(job)) %>
    </td>
    <td>
     <%= link_to(job.location, job_path(job)) %>
    </td>
    <td width="30%">
     <span class="label label-info">
      <span class="fa fa-rmb"></span>
      <%= job.wage_lower_bound%> - <%= job.wage_upper_bound%> 元
    </span>
    </td>
    <td width="10%">
      <%= local_time(job.require_time, '%B %e, %Y') %>
    </td>
    <td width="10%">
      <%= local_time(job.created_at, '%B %e, %Y') %>
    </td>
  </tr>

app/views/jobs/edit.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">


		<!-- Website CSS style -->
		<link href="css/bootstrap.min.css" rel="stylesheet">

		<!-- Website Font style -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
		<link rel="stylesheet" href="style.css">
		<!-- Google Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

		<title>Edit</title>
	</head>

  <!-- <body background="/images/bk.png"> -->

    <div class="container">
    <div class="row main">
      <div class="main-left">
      <h1> 编辑工作</h1>
      <br>
      <br>
          <%= simple_form_for @job do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <div class="cols-sm-10">
                <%= f.input :title, required: true, autofocus: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :description %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :city, :label=> "城市", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :location, :label => "区域", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :field, :label => "种类", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :require_time, :label => "需要时间", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :wage_lower_bound, :label => "薪资下限", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :wage_upper_bound, :label => "薪资上限", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input  :contact_email, :label => "联系邮箱", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :is_hidden, as: :boolean  %>
            </div>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "提交" %>
          </div>
          <% end %>

      </div>
      </div>
      </div>


    
      </body>
      </html>

app/views/jobs/index.html.erb
<!-- <div class="dropdown clearfix pull-right open">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      排序
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
        <li>
          <%= link_to("按照薪资下限排序", jobs_path(:order => "by_lower_bound")) %>
        </li>
        <li>
            <%= link_to("按照薪资上限排序", jobs_path(:order => "by_upper_bound")) %>

        </li>
        <li>
          <%= link_to("按照发表时间排序", jobs_path ) %>

        </li>
    </ul>
</div> -->

<br>
<br>

<div class="form-group">
<div class="btn-group pull-left" role="group" aria-label="...">
     <%= link_to("按薪资下限排序", search_jobs_path(:order => "by_lower_bound", :query_string => @query), :class => "btn btn-default") %>
     <%= link_to("按薪资上限排序", search_jobs_path(:order => "by_upper_bound", :query_string => @query), :class => "btn btn-default") %>
     <%= link_to("按需求时间排序", search_jobs_path(:order => "by_require_time", :query_string => @query), :class => "btn btn-default") %>
     <%= link_to("按发表时间排序", search_jobs_path(:order => "by_require_time", :query_string => @query), :class => "btn btn-default") %>
</div>
<div class="pull-right">
  <%= link_to("Add a job", new_job_path, :class => "btn btn-info" ) %>
</div>
</div>

<div class="item_div">
<!-- <table class="table table-boldered"> -->
<table class="table table-boldered table-striped " >
  <thead>
    <tr>
      <td>需求</td>
      <td>种类</td>
      <td>城市</td>
      <td>区域</td>
      <td>薪资范围</td>
      <td>需求时间</td>
      <td>刊登时间</td>
    </tr>
  </thead>
  <tbody>
  <% @jobs.each do |job| %>
  <tr>
    <td>
      <%= link_to(job.title, job_path(job)) %>
    </td>
    <!-- <td>
     <i class="fa fa-fire"></i>
   </td> -->
    <td>
     <%= link_to(job.field, job_path(job)) %>
    </td>
    <td>
     <%= link_to(job.city, job_path(job)) %>
    </td>
    <td>
     <%= link_to(job.location, job_path(job)) %>
    </td>
    <td width="30%">
     <span class="label label-info">
      <span class="fa fa-rmb"></span>
      <%= job.wage_lower_bound%> - <%= job.wage_upper_bound%> 元
    </span>
    </td>
    <td width="10%">
      <%= local_time(job.require_time, '%B %e, %Y') %>
    </td>
    <td width="10%">
      <%= local_time(job.created_at, '%B %e, %Y') %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>
</div>

<div class="text-center" >
    <%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>
</div>

app/views/jobs/new.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">


		<!-- Website CSS style -->
		<link href="css/bootstrap.min.css" rel="stylesheet">

		<!-- Website Font style -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
		<link rel="stylesheet" href="style.css">
		<!-- Google Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

		<title>New</title>
	</head>

  <!-- <body background="/images/bk.png"> -->

    <div class="container">
    <div class="row main">
      <div class="main-left">
      <h1> 新增工作 </h1>
      <br>
      <br>
          <%= simple_form_for @job do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <div class="cols-sm-10">
                <%= f.input :title, required: true, autofocus: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :description %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :city, :label=> "城市", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :location, :label => "区域", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :field, :label => "种类", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :require_time, :label => "需要时间", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :wage_lower_bound, :label => "薪资下限", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :wage_upper_bound, :label => "薪资上限", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input  :contact_email, :label => "联系邮箱", required: true %>
            </div>
            <div class="cols-sm-10">
                <%= f.input :is_hidden, as: :boolean  %>
            </div>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "提交" %>
          </div>
          <% end %>

      </div>
      </div>
      </div>



      </body>
      </html>

app/views/jobs/search.html.erb
<br>
<br>
<div class="form-group">
<div class="btn-group pull-left" role="group" aria-label="...">
     <%= link_to("按薪资下限排序", search_jobs_path(:order => "by_lower_bound", :query_string => @query), :class => "btn btn-default") %>
     <%= link_to("按薪资上限排序", search_jobs_path(:order => "by_upper_bound", :query_string => @query), :class => "btn btn-default") %>
     <%= link_to("按需求时间排序", search_jobs_path(:order => "by_require_time", :query_string => @query), :class => "btn btn-default") %>
     <%= link_to("按发表时间排序", search_jobs_path(:order => "by_require_time", :query_string => @query), :class => "btn btn-default") %>
</div>
<div class="pull-right">
  <%= link_to("Add a job", new_job_path, :class => "btn btn-info" ) %>
</div>
</div>


<div class="item_div">
        <table class="table table-boldered table-striped custab" >
          <thead>
            <tr>
              <td>需求</td>
              <td>种类</td>
              <td>城市</td>
              <td>区域</td>
              <td>薪资范围</td>
              <td>需求时间</td>
              <td>刊登时间</td>
            </tr>
          </thead>
          <tbody>
          <%= render :partial => "jobs/item", :collection => @jobs, :as => :job %>
          </tbody>
        </table>
</div>

        <div class="text-center" >
            <%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>
        </div>

app/views/jobs/show.html.erb
<div class="container">
	<div class="row-fluid">
        <div class="span8">
        	<iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?f=q&source=s_q&hl=en&geocode=&q=15+Springfield+Way,+Hythe,+CT21+5SH&aq=t&sll=52.8382,-2.327815&sspn=8.047465,13.666992&ie=UTF8&hq=&hnear=15+Springfield+Way,+Hythe+CT21+5SH,+United+Kingdom&t=m&z=14&ll=51.077429,1.121722&output=embed"></iframe>
    	</div>

      	<div class="span4">
    		<h2> <%= @job.title %> </h2>
        <h3><%= @job.description %><br></h3>
    		<address>
    			<h4><strong> <%= @job.city %></strong><br></h4>
          <strong><%= @job.location %>
    			余姚路328号<br></strong>

    			</strong><abbr title="Phone">P:</abbr> 13761178672</strong>
    		</address>
    	</div>
    </div>
</div>


<div class="text-center">
  <%= link_to("应征", new_job_resume_path(@job), :class => "btn btn-info") %>
</div>